### ISSUE TITLE
Problem with ® char

### ISSUE THREAD

**Issue by pauldruziak** [thoughtbot/griddler#165]
I added commit that show the problem:  paveldruzyak/griddler@73f80165627820460435128e20d93ad2914c232d

```
Failures:

  1) Griddler::Email body formatting handles invalid utf-8 char in text
     Failure/Error: expect(body_from_email(text: "Hell\xF6\xC2\xAE.")).to eq 'Hellö®.'

       expected: "Hellö®."
            got: "HellöÂ®."

       (compared using ==)
     # ./spec/griddler/email_spec.rb:32:in `block (2 levels) in <top (required)>'
```

Any ideas how it can be fixed?
